<?php

namespace Ideato\Bundle\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getLastestPost()
    {
        return $this->getEntityManager()
                ->createQuery("SELECT p FROM IdeatoBlogBundle:Post p ORDER BY p.publicationDate DESC")
                ->getResult();
    }
    
    public function gePostByAuthorId()
    {
        $q = $this->createQueryBuilder('p')
                ->where('p.title = :title')
                ->orderBy('p.publicationDate');
        $q->setParameter("title","Post title #0");
    }
}